version: '3'
services:
    nginx:
        image: ${NGINX_IMAGE}
        container_name: ${NGINX_CONTAINER_NAME}
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './conf.d:/etc/nginx/conf.d/'
            - './nginx.conf:/etc/nginx/nginx.conf'
            - './ssl:/etc/nginx/ssl/'
            - './html:/etc/nginx/html/'
            - './letsencrypt:/etc/letsencrypt'
            - './certbot:/var/www/certbot'
        environment:
            - TZ=Europe/Paris
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: ${CERTBOT_IMAGE}
        container_name: ${CERTBOT_CONTAINER_NAME}
        restart: unless-stopped
        volumes:
            - './letsencrypt:/etc/letsencrypt'
            - './certbot:/var/www/certbot'
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
    default:
        external:
            name: main
