version: '3'
services:
    nginx:
        image: ${NGINX_IMAGE}
        container_name: ${NGINX_CONTAINER_NAME}
        ports:
            - '80:80'
            - '443:443'
            - '10050:10050'
            - '10051:10051'
        volumes:
            - './conf.d:/etc/nginx/conf.d/'
            - './nginx.conf:/etc/nginx/nginx.conf'
            - './ssl:/etc/nginx/ssl/'
        environment:
            - TZ=Europe/Paris
networks:
    default:
        external:
            name: main
